# Les Listes 

###1. Listes :
Exercice 1 :
####	Créez une liste de 10 nombres entiers.
####    Calculez la somme de tous les éléments de la liste.
####    Trouvez l'élément maximum et minimum de la liste.
####    Créez une nouvelle liste en doublant chaque valeur de la liste d'origine.


In [19]:
# Créer une liste de 10 nombres entiers 

ma_liste = []
for i in range(0,10,1):
    ma_liste.append(i)
print(ma_liste)

[0, 1, 2, 3, 4, 5, 6, 7, 8, 9]


In [20]:
# Calculez la somme de tous les éléments de la liste
Ma_liste = sum(ma_liste)
Ma_liste

45

In [22]:
# Trouvez l'élément maximum et minimum de la liste. 

Ma_liste = ma_liste
minimum = min(ma_liste)
maximum = max(ma_liste)
print("Le minimum de la liste est : ", minimum)
print("Le maximum de la liste est : ", maximum)

Le minimum de la liste est :  0
Le maximum de la liste est :  9


In [3]:
# Créez une nouvelle liste en doublant chaque valeur de la liste d'origine.
# Avec la boucle for
ma_liste = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
ma_liste_double = []
for i in ma_liste:
    ma_liste_double.append(i * 2)
print( ma_liste_double)

[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


In [2]:
ma_liste = [0, 1, 2, 3, 4, 5, 6, 7, 8, 9]
ma_liste_double = [i * 2 for i in ma_liste]
print(ma_liste_double)


[0, 2, 4, 6, 8, 10, 12, 14, 16, 18]


# Exercice 2 :
### Créez une liste contenant des prénoms.
### Ajoutez un prénom au début de la liste, puis supprimez le dernier prénom de la liste.
### Affichez la liste après chaque modification.
### Utilisez une boucle pour afficher tous les prénoms de la liste avec un indice.


In [6]:
# Créer une liste de prénoms
mes_prenoms = ["Fatou", "Saliou", "Mamadou"]
print (mes_prenoms)

['Fatou', 'Saliou', 'Mamadou']


In [13]:
# Ajouter un prénom au début de la liste
mes_prenoms.insert(0,"Sonko")
mes_prenoms


['Sonko', 'Sonko', 'Fatou', 'Saliou', 'Mamadou']

In [15]:
# Ajouter une liste au début 
noms = ["Eulalie", "Faye", "Sow"]
noms.insert(0, "Saounera")
noms

['Saounera', 'Eulalie', 'Faye', 'Sow']

In [16]:
# Ajouter un nom à la fin 
noms_fin = ["Sonko", "DIEDHIOU", "Moussa"]
noms_fin.append("Coly")
noms_fin

['Sonko', 'DIEDHIOU', 'Moussa', 'Coly']

In [23]:
# Ajouter plusieurs noms à la fin 
noms_fin.extend(["Diarra", "Diaw"])
noms_fin

['Sonko',
 'DIEDHIOU',
 'Moussa',
 'Coly',
 'D',
 'i',
 'a',
 'r',
 'r',
 'a',
 'Diarra',
 'Diaw',
 'Diarra',
 'Diaw',
 'Papis',
 'Diaw',
 'Diarra',
 'Diaw']

In [24]:
noms_fin = ["Fatou", "Saliou", "Mamadou"]
noms_a_ajouter = ["Diarra", "Diaw"]

for nom in noms_a_ajouter:
    noms_fin.append(nom)

print(noms_fin)


['Fatou', 'Saliou', 'Mamadou', 'Diarra', 'Diaw']


In [33]:
# Utiliser une boucle pour afficher les prénoms avec leur indice
for indice, prenom in enumerate(ma_liste):
    print(f"Indice {indice} : {prenom}")


Indice 0 : Sow
Indice 1 : Fatou
Indice 2 : Mame


# Exercice 3 :


#### Créez un dictionnaire avec les noms des mois de l'année comme clés et les numéros de mois comme valeurs.
#### Demandez à l'utilisateur d'entrer un mois (par exemple "Janvier") et affichez son numéro dans l'année.
#### Modifiez le dictionnaire pour y ajouter un mois fictif, puis supprimez-en un autre.



In [34]:
# Créez un dictionnaire avec les noms des mois de l'année comme clés et les numéros de mois comme valeurs.
mon_dico = {
"janvier" : 1,
"fevrier" : 2, 
"mars" : 3,
"avril" : 4,
"mai" : 5,
"juin" : 6, 
"juillet" : 7,
"aout" : 8, 
"septembre" : 9, 
"octobre" : 10,
"novembre" : 11, 
"decembre" : 12
}
print (mon_dico)

{'janvier': 1, 'fevrier': 2, 'mars': 3, 'avril': 4, 'mai': 5, 'juin': 6, 'juillet': 7, 'aout': 8, 'septembre': 9, 'octobre': 10, 'novembre': 11, 'decembre': 12}


In [ ]:
# Demandez à l'utilisateur d'entrer un mois (par exemple "Janvier") et affichez son numéro dans l'année

# Modifiez le dictionnaire pour y ajouter un mois fictif, puis supprimez-en un autre
mon_dico["Papis"] = 13
mon_dico

In [39]:
# Supprimer l'élement fictif
mon_dico.pop("Papis")
mon_dico

{'janvier': 1,
 'fevrier': 2,
 'mars': 3,
 'avril': 4,
 'mai': 5,
 'juin': 6,
 'juillet': 7,
 'aout': 8,
 'septembre': 9,
 'octobre': 10,
 'novembre': 11,
 'decembre': 12}

# Exercice 4 :



#####   Créez un dictionnaire avec des informations sur une personne (nom, âge, ville).
#####   Utilisez des fonctions pour ajouter et modifier des informations dans le dictionnaire.
#####   Utilisez une boucle pour afficher chaque clé et valeur du dictionnaire.

In [42]:
# Créez un dictionnaire avec des informations sur une personne (nom, âge, ville).
donnees_personnelles = {
"nom" : "Papis",
"age" : 18,
"ville" : "Kolda"
}
donnees_personnelles

{'nom': 'Papis', 'age': 18, 'ville': 'Kolda'}

In [43]:
# Utilisez des fonctions pour ajouter et modifier des informations dans le dictionnaire.
#Ajout au début du dico 
donnees_personnelles["Lieu de naissance"] = "Kolda"
donnees_personnelles

{'nom': 'Papis', 'age': 18, 'ville': 'Kolda', 'Lieu de naissance': 'Kolda'}

In [44]:
#Modifier des informations dans le dictionnaire 
donnees_personnelles["age"] = 25
donnees_personnelles

{'nom': 'Papis', 'age': 25, 'ville': 'Kolda', 'Lieu de naissance': 'Kolda'}

In [52]:
# Utilisez une boucle pour afficher chaque clé et valeur du dictionnaire.

donnees_personnelles = {
    'nom': 'Papis',
    'age': 25,
    'ville': 'Kolda',
    'Lieu de naissance': 'Kolda'
}

# Parcourir chaque clé et valeur
for cle, valeur in donnees_personnelles.items():
    print(f"Clé : {cle}, Valeur : {valeur}")


Clé : nom, Valeur : Papis
Clé : age, Valeur : 25
Clé : ville, Valeur : Kolda
Clé : Lieu de naissance, Valeur : Kolda


In [53]:
noms = {" nom" : "SANE",
"Prenom" : "Fatou",
"Ville" : "Ziguinchor"
}
noms

{' nom': 'SANE', 'Prenom': 'Fatou', 'Ville': 'Ziguinchor'}

# Exercice 5 :


## Créez un tuple contenant des valeurs (int, float, string).
## Essayez de modifier une valeur du tuple (ce qui devrait échouer).
## Créez un nouveau tuple en combinant celui-ci avec un autre.




In [55]:
mon_tuple =  (15, 1.5, "Fatou")
mon_tuple

(15, 1.5, 'Fatou')

In [57]:
# Créez un nouveau tuple en combinant celui-ci avec un autre
mon_tuple1= (1, 15, 102, 'fatou')
tuple_2 = ("faty", 1.08, 3, "x")
print (mon_tuple + tuple_2)

(15, 1.5, 'Fatou', 'faty', 1.08, 3, 'x')


# Exercice 6 :


In [1]:
# Créez un tuple avec 5 éléments et utilisez un indice négatif pour accéder aux éléments à partir de la fin du tuple.
manchester = ("Ronaldo", "Rooney", "Van Nistelrooy", 10, 1.5)
manchester 

('Ronaldo', 'Rooney', 'Van Nistelrooy', 10, 1.5)

In [3]:
mon_dernier = manchester[-1]
mon_dernier

1.5

In [4]:
avant_dernier = manchester[-2]
avant_dernier

10

In [6]:
# Affichez le tuple, la longueur du tuple, et l'élément à l'indice 2
man = manchester[2]
man

'Van Nistelrooy'

In [17]:
len(manchester)



5

# Exercice 7 :

In [24]:
# Utilisez une boucle for pour imprimer les nombres de 1 à 10
for i in range(1,11,1):
    print(i)

1
2
3
4
5
6
7
8
9
10


In [27]:
# Utilisez une boucle for pour imprimer tous les nombres impairs entre 1 et 20.
for i in range(1,21, 1):
    if i % 2 != 0:
        print(f"Ce chiffre {i} est impair")

Ce chiffre 1 est impair
Ce chiffre 3 est impair
Ce chiffre 5 est impair
Ce chiffre 7 est impair
Ce chiffre 9 est impair
Ce chiffre 11 est impair
Ce chiffre 13 est impair
Ce chiffre 15 est impair
Ce chiffre 17 est impair
Ce chiffre 19 est impair


In [33]:
# Utilisez une boucle while pour imprimer tous les nombres impairs entre 1 et 20.
ma_liste = 1 # Initialisation de la variable à 1 
while ma_liste  <= 20 : # Utiliser une boucle while pour imprimer tous les nombres impairs entre 1 et 20
    if ma_liste % 2 != 0 : # Vérifier si le nombre est impair
        print(ma_liste) # Afficher le nombre impair
    ma_liste +=   # Incrémenter la variable


1
3
5
7
9
11
13
15
17
19


In [34]:
mon_compteur = 0
while mon_compteur <= 20: 
    if mon_compteur % 2 != 0:
        print(f"Ce chiffre {mon_compteur} est impair")
    mon_compteur +=1

Ce chiffre 1 est impair
Ce chiffre 3 est impair
Ce chiffre 5 est impair
Ce chiffre 7 est impair
Ce chiffre 9 est impair
Ce chiffre 11 est impair
Ce chiffre 13 est impair
Ce chiffre 15 est impair
Ce chiffre 17 est impair
Ce chiffre 19 est impair


# Exercice 8 : 


In [42]:
# Utilisez une boucle for pour parcourir une liste et afficher "pair" ou "impair" pour chaque élément.
ma_liste_paire_impaire = [1, 15, 2, 19, 18, 34, 45, 98, 20]
for i in ma_liste_paire_impaire: 
    if i % 2 == 0: 
        print(f"Le nombre {i} est pair") 
    else: 
        print(f"Le nombre {i} est impair")

Le nombre 1 est impair
Le nombre 15 est impair
Le nombre 2 est pair
Le nombre 19 est impair
Le nombre 18 est pair
Le nombre 34 est pair
Le nombre 45 est impair
Le nombre 98 est pair
Le nombre 20 est pair


# Exercice 9 :


In [ ]:
# Utilisez une boucle while pour donner des indices et répéter la tentative jusqu'à ce que la réponse soit correcte.

##### import random

# Générer un nombre aléatoire entre 1 et 10
nombre_a_deviner = random.randint(1, 10)

print("Bienvenue dans le jeu de devinette !")
print("Je pense à un nombre entre 1 et 10. Vous avez 3 essais pour deviner lequel !")

# Initialiser le compteur d'essais
essais_restants = 3

while essais_restants > 0:
    try:
        reponse = int(input(f"Vous avez {essais_restants} essai(s) restant(s). Entrez votre nombre : "))
    except ValueError:
        print("Veuillez entrer un nombre valide.")
        continue

    if reponse < nombre_a_deviner:
        print("C'est plus grand !")
    elif reponse > nombre_a_deviner:
        print("C'est plus petit !")
    else:
        print(f"Bravo ! Vous avez deviné le nombre {nombre_a_deviner}.")
        break  # Sortir de la boucle si le nombre est deviné

    essais_restants -= 1  # Réduire le nombre d'essais restants

if essais_restants == 0:
    print(f"Dommage, vous avez perdu ! Le nombre à deviner était {nombre_a_deviner}.")


# Les Fonctions :


## Exercice 10 :


In [2]:
# Créez une fonction addition(a, b) qui retourne la somme de deux nombres.
addition = lambda a, b : a + b
print (addition(2,6))


8


In [12]:
# Créez une fonction factorielle(n) qui calcule la factorielle d’un nombre donné.
def factorielle(n):
    """
    Calcule la factorielle d'un nombre donné.
    :param n: Nombre entier non négatif.
    :return: Factorielle de n.
    """
    if n < 0:
        return "La factorielle n'est pas définie pour les nombres négatifs."
    elif n == 0 or n == 1:
        return 1
    else:
        resultat = 1
        for i in range(2, n + 1):
            resultat *= i
        return resultat

# Exemple d'utilisation :
nombre = 5
print(f"La factorielle de {nombre} est {factorielle(nombre)}.")


La factorielle de 5 est 120.


In [13]:
# Créez une fonction reverse_string(s) qui retourne une chaîne de caractères inversée.
def reverse_string(s):
    """
    Retourne la chaîne de caractères inversée.
    :param s: Chaîne de caractères.
    :return: Chaîne inversée.
    """
    return s[::-1]

# Exemple d'utilisation :
texte = "Bonjour"
print(f"La chaîne inversée de '{texte}' est '{reverse_string(texte)}'.")


La chaîne inversée de 'Bonjour' est 'ruojnoB'.


# Exercice 11 :


##### Créez une fonction est_pair(n) qui vérifie si un nombre est pair ou impair, et l'utilise dans un programme qui demande à l'utilisateur de saisir 
# un nombre.

def est_pair(n):
    """
    Vérifie si un nombre est pair ou impair.
    :param n: Nombre entier.
    :return: True si le nombre est pair, False sinon.
    """
    return n % 2 == 0

# Programme principal
try:
    nombre = int(input("Veuillez entrer un nombre entier : "))
    if est_pair(nombre):
        print(f"Le nombre {nombre} est pair.")
    else:
        print(f"Le nombre {nombre} est impair.")
except ValueError:
    print("Veuillez entrer un nombre valide.")



In [23]:
def addition (n,m):
    return n+m
print(addition(5,3))

8


In [26]:
addition = lambda m, n : n + m
print(addition(5,5));

10


# NumPy :

### Exercice 12 :

In [27]:
# import numpy
import numpy as np


In [28]:
# Créez un tableau NumPy de 10 éléments allant de 1 à 10.
tableau = np.arange(1,11)
print(tableau)

[ 1  2  3  4  5  6  7  8  9 10]


In [33]:
# Calculez la moyenne, la somme et l'écart type de ce tableau.
Somme = np.sum(tableau)
Moyenne = np.mean(tableau)
Ecart_Type = np.std(tableau)
print ("La somme de la série est de : " , Somme)
print ("La Moyenne de la série est de : ", Moyenne)
print ("L'écart type de la série est : " , Ecart_Type)

La somme de la série est de :  55
La Moyenne de la série est de :  5.5
L'écart type de la série est :  2.8722813232690143


In [41]:
# Créez un tableau 2D (matrice) de taille 3x3 avec des valeurs aléatoires et trouvez le maximum et le minimum de cette matrice.
matrice = np.random.randint(1,21, size = (3,3))
Valeur_max = np.max(matrice)
Valeur_min = np.min(matrice)
print ("M a matrice : ", matrice)
print (f"La valeur maximale de la série est :  {Valeur_max}" )
print (f"La valeur minimale de la série est :  {Valeur_min} ")


M a matrice :  [[ 7 19 20]
 [ 7 15 13]
 [15  7  7]]
La valeur maximale de la série est :  20
La valeur minimale de la série est :  7 


# Exercice 13 :

In [44]:
# Créez un tableau NumPy contenant des nombres de 1 à 20.
mon_tableau = np.arange(1, 21)
print (mon_tableau)

[ 1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20]


In [47]:
# Utilisez des opérations vectorisées pour ajouter 5 à chaque élément du tableau.
for i in mon_tableau:
    resultat = mon_tableau + 5
print(resultat)


[ 6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23 24 25]


In [53]:
# Utilisez des masques pour sélectionner et afficher uniquement les éléments supérieurs à 10.
elements_sup_10 = mon_tableau[mon_tableau > 10]
print (elements_sup_10)


[11 12 13 14 15 16 17 18 19 20]


# Pandas :


### Exercice 14 :


In [75]:
# Créez un DataFrame Pandas avec des données simples (par exemple, noms, âges et professions).
import pandas as pd

In [78]:
# Créez un DataFrame Pandas avec des données simples (par exemple, noms, âges et professions).
import pandas as pd

mon_df = {
    "nom" : ["DIEDHIOU", "SONKO", "DIAO", "GOUDIABY", "TRAORE", "GOMIS", "SOW", "SANE", "BALDE", "DIATTA", "BADJI"],
    "age" : [37, 32, 30, 33, 39, 36, 38, 35, 39, 40, 41],
    "profession" : ["chômeur", "ménager", "enseignant", "soudeur", "pêcheur", "footballeur", "réceptionniste", "maçon", "coffreur", "vendeur", "chauffeur"]
}
df = pd.DataFrame(mon_df)
df

nom  age      profession
0   DIEDHIOU   37         chômeur
1      SONKO   32         ménager
2       DIAO   30      enseignant
3   GOUDIABY   33         soudeur
4     TRAORE   39         pêcheur
5      GOMIS   36     footballeur
6        SOW   38  réceptionniste
7       SANE   35           maçon
8      BALDE   39        coffreur
9     DIATTA   40         vendeur
10     BADJI   41       chauffeur

In [89]:
import pandas as pd
df_data = {
    "nom" : ["Mame", "Awa", "Pape"],
    "Nom" : ["Sonko", "Diallo", "Diedhiou"],
    "age" : [6, 18, 20]
}
df = pd.DataFrame(df_data)
df


nom       Nom  age
0  Mame     Sonko    6
1   Awa    Diallo   18
2  Pape  Diedhiou   20

In [91]:
mon_dataframe = {
    "ville" : ["Saint Louis", "Dakar", "KOLDA", "Thies"],
    "superficie" : [7500, 550, 29008, 10085],
    "annee creation" : ["1950", "1854", "1984", "1960"]
}
df = pd.DataFrame(mon_dataframe)
df


ville  superficie annee creation
0  Saint Louis        7500           1950
1        Dakar         550           1854
2        KOLDA       29008           1984
3        Thies       10085           1960

In [95]:
import pandas as pd

# Définition du dictionnaire
mon_df = {
    "nom": ["DIEDHIOU", "SONKO", "DIAO", "GOUDIABY", "TRAORE", "GOMIS", "SOW", "SANE", "BALDE", "DIATTA", "BADJI"],
    "age": [37, 32, 30, 33, 39, 36, 38, 35, 39, 40, 41],
    "profession": ["chômeur", "ménager", "enseignant", "soudeur", "pêcheur", "footballeur", "réceptionniste", "maçon", "coffreur", "vendeur", "chauffeur"]
}

# Création du DataFrame
df = pd.DataFrame(mon_df)

# Affichage du DataFrame
print(df)


         nom  age      profession
0   DIEDHIOU   37         chômeur
1      SONKO   32         ménager
2       DIAO   30      enseignant
3   GOUDIABY   33         soudeur
4     TRAORE   39         pêcheur
5      GOMIS   36     footballeur
6        SOW   38  réceptionniste
7       SANE   35           maçon
8      BALDE   39        coffreur
9     DIATTA   40         vendeur
10     BADJI   41       chauffeur


In [96]:
# Affichez les 5 premières lignes du DataFrame.
df.head()


nom  age  profession
0  DIEDHIOU   37     chômeur
1     SONKO   32     ménager
2      DIAO   30  enseignant
3  GOUDIABY   33     soudeur
4    TRAORE   39     pêcheur

In [107]:
# Sélectionnez uniquement les lignes où l'âge est supérieur à 30.

import pandas as pd

# Dictionnaire initial
mon_df = {
    "nom": ["DIEDHIOU", "SONKO", "DIAO", "GOUDIABY", "TRAORE", "GOMIS", "SOW", "SANE", "BALDE", "DIATTA", "BADJI"],
    "age": [37, 32, 30, 33, 39, 36, 38, 35, 39, 40, 41],
    "profession": ["chômeur", "ménager", "enseignant", "soudeur", "pêcheur", "footballeur", "réceptionniste", "maçon", "coffreur", "vendeur", "chauffeur"]
}

# Conversion en DataFrame Pandas
df = pd.DataFrame(mon_df)

# Filtrer les lignes où l'âge est supérieur à 35
df_filtre = df[df["age"] > 35]

# Afficher le DataFrame filtré
print(df_filtre)





         nom  age      profession
0   DIEDHIOU   37         chômeur
4     TRAORE   39         pêcheur
5      GOMIS   36     footballeur
6        SOW   38  réceptionniste
8      BALDE   39        coffreur
9     DIATTA   40         vendeur
10     BADJI   41       chauffeur


# Exercice 15 :


In [120]:
# Créez un DataFrame Pandas avec des données de ventes (produit, quantité, prix unitaire).
import pandas as pd

ventes = {
"Produits" : ["Sacs", "Chaussures", "Ballons"],
"Quantités" : [ 250, 1100, 600],
"Prix unitaires" : [6000, 22000, 12000]
}
df_ventes = pd.DataFrame(ventes)
df_ventes


Produits  Quantités  Prix unitaires
0        Sacs        250            6000
1  Chaussures       1100           22000
2     Ballons        600           12000

In [126]:
# Calculez le total des ventes pour chaque produit en créant une nouvelle colonne "Total".

df_ventes["Total"] = df_ventes["Quantités"] * df_ventes["Prix unitaires"]
df_ventes

Produits  Quantités  Prix unitaires     Total
0        Sacs        250            6000   1500000
1  Chaussures       1100           22000  24200000
2     Ballons        600           12000   7200000

In [129]:
# Affichez les résultats triés par total des ventes

In [145]:
mon_tableau = {

"Produits" : ["Sacs", "Ballons", "Plots", "Chaussures", "Tables"],
"Quantités" : [150, 600, 1800, 1100, 20],
"Prix unitaire" : [5.6, 18.25, 1.5, 23.5, 55.33]
}
df_mon_tableau = pd.DataFrame(mon_tableau)
df_mon_tableau["Total"] = df_mon_tableau["Quantités"] * df_mon_tableau["Prix unitaire"]
df_trie = df_mon_tableau.sort_values (by = "Total", ascending =False)
df_mon_tableau


Produits  Quantités  Prix unitaire    Total
0        Sacs        150           5.60    840.0
1     Ballons        600          18.25  10950.0
2       Plots       1800           1.50   2700.0
3  Chaussures       1100          23.50  25850.0
4      Tables         20          55.33   1106.6

# Exercice 16 :

In [153]:
# Montre le répertoire actuel
import os
print(os.getcwd())  # Montre le répertoire actuel


C:\Users\DIEDHIOU\Exercice d'application


In [162]:
df = pd.read_csv("D:\Python_Analyse_de_données\donnees_marketing_banque.csv", sep = ";",  encoding='utf-8')
df



id  age           job   marital  education default  balance  \
0          id1   58    management   married   tertiary      no   2143.0   
1          id2   44    technician    single  secondary      no     29.0   
2          id3   33  entrepreneur   married  secondary      no      2.0   
3          id4   47   blue-collar   married    unknown      no   1506.0   
4          id5   33       unknown    single    unknown      no      1.0   
...        ...  ...           ...       ...        ...     ...      ...   
45206  id45207   51    technician   married   tertiary      no    825.0   
45207  id45208   71       retired  divorced    primary      no   1729.0   
45208  id45209   72       retired   married  secondary      no   5715.0   
45209  id45210   57   blue-collar   married  secondary      no    668.0   
45210  id45211   37  entrepreneur   married  secondary      no   2971.0   

      housing loan    contact  day month  duration  campaign  pdays  previous  \
0         yes   no    unknown    5   may       261         1     -1         0   
1         yes   no    unknown    5   may       151         1     -1         0   
2         yes  yes    unknown    5   may        76         1     -1         0   
3         yes   no    unknown    5   may        92         1     -1         0   
4          no   no    unknown    5   may       198         1     -1         0   
...       ...  ...        ...  ...   ...       ...       ...    ...       ...   
45206      no   no   cellular   17   nov       977         3     -1         0   
45207      no   no   cellular   17   nov       456         2     -1         0   
45208      no   no   cellular   17   nov      1127         5    184         3   
45209      no   no  telephone   17   nov       508         4     -1         0   
45210      no   no   cellular   17   nov       361         2    188        11   

      poutcome    y  
0      unknown   no  
1      unknown   no  
2      unknown   no  
3      unknown   no  
4      unknown   no  
...        ...  ...  
45206  unknown  yes  
45207  unknown  yes  
45208  success  yes  
45209  unknown   no  
45210    other   no  

[45211 rows x 18 columns]

In [ ]:
C:\Users\DIEDHIOU\Exercice d'application/donnees_marketing_banque.csv

In [165]:
# Utiliser df.describe() et sélectionner des lignes spécifiques
stats_selection = df.describe().loc[["count", "min", "max"]]
print(stats_selection)


           age   balance      day  duration  campaign    pdays  previous
count  45211.0   45206.0  45211.0   45211.0   45211.0  45211.0   45211.0
min       10.0   -8019.0      1.0       0.0       1.0     -1.0       0.0
max       95.0  102127.0     31.0    4918.0      63.0    871.0     275.0


In [166]:
# Affichez les informations sur le DataFrame (nombre de lignes et colonnes).
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 45211 entries, 0 to 45210
Data columns (total 18 columns):
 #   Column     Non-Null Count  Dtype  
---  ------     --------------  -----  
 0   id         45211 non-null  object 
 1   age        45211 non-null  int64  
 2   job        45211 non-null  object 
 3   marital    45211 non-null  object 
 4   education  45211 non-null  object 
 5   default    45211 non-null  object 
 6   balance    45206 non-null  float64
 7   housing    45211 non-null  object 
 8   loan       45211 non-null  object 
 9   contact    45211 non-null  object 
 10  day        45211 non-null  int64  
 11  month      45211 non-null  object 
 12  duration   45211 non-null  int64  
 13  campaign   45211 non-null  int64  
 14  pdays      45211 non-null  int64  
 15  previous   45211 non-null  int64  
 16  poutcome   45211 non-null  object 
 17  y          45211 non-null  object 
dtypes: float64(1), int64(6), object(11)
memory usage: 6.2+ MB


In [168]:
df.shape

(45211, 18)

In [169]:
# Recherchez une valeur spécifique dans une colonne et effectuez un filtrage.

resultat = df[df["job"] == "management"]
print(resultat)


            id  age         job  marital  education default  balance housing  \
0          id1   58  management  married   tertiary      no   2143.0     yes   
5          id6   35  management  married   tertiary      no    231.0     yes   
6          id7   28  management   single   tertiary      no    447.0     yes   
21        id22   56  management  married   tertiary      no    779.0     yes   
26        id27   12  management   single   tertiary      no    255.0     yes   
...        ...  ...         ...      ...        ...     ...      ...     ...   
45192  id45193   29  management   single   tertiary      no    765.0      no   
45194  id45195   59  management  married   tertiary      no    138.0     yes   
45197  id45198   36  management   single  secondary      no   1511.0     yes   
45198  id45199   37  management  married   tertiary      no   1428.0      no   
45201  id45202   53  management  married   tertiary      no    583.0      no   

      loan   contact  day month  durati

# Exercice 17 :


In [172]:
# Créez un dictionnaire où les clés sont des prénoms et les valeurs sont des âges.
mon_dictionnaire = {
"Fatou" : 28, 
"Amadou" : 25, 
"Coly" : 45, 
"John" : 16, 
"Seydou" : 25
}
print (mon_dictionnaire)

{'Fatou': 28, 'Amadou': 25, 'Coly': 45, 'John': 16, 'Seydou': 25}


In [173]:
mon_dictionnaire = {
    "Fatou": 28,
    "Amadou": 35,
    "Coly": 18,
    "John": 45,
    "Seydou": 52
}

print(mon_dictionnaire)


{'Fatou': 28, 'Amadou': 35, 'Coly': 18, 'John': 45, 'Seydou': 52}


In [183]:
# Convertissez ce dictionnaire en un DataFrame Pandas et ajoutez une nouvelle colonne "Année de naissance" calculée en fonction de l'âge.
mon_dictionnaire = {
"Prenoms" : ["Fatou", "Amadou", "Coly", "John", "Seydou"],
"Age" : [28, 35, 18, 45, 52]
}
df_mon_dictionnaire = pd.DataFrame(mon_dictionnaire)
df_mon_dictionnaire["Annee_Actuelle"] = pd.Timestamp.now().year
df_mon_dictionnaire["Annee_naissance"] = df_mon_dictionnaire["Annee_Actuelle"] - df_mon_dictionnaire["Age"]
df_mon_dictionnaire

Prenoms  Age  Annee_Actuelle  Annee_naissance
0   Fatou   28            2024             1996
1  Amadou   35            2024             1989
2    Coly   18            2024             2006
3    John   45            2024             1979
4  Seydou   52            2024             1972

# Exercice 18 :

In [184]:
# Créez une liste de tuples représentant des coordonnées géographiques (latitude, longitude).

coordonnees = [
    (48.8566, 2.3522),  # Paris, France
    (40.7128, -74.0060),  # New York, USA
    (34.0522, -118.2437),  # Los Angeles, USA
    (51.5074, -0.1278),  # Londres, Royaume-Uni
    (35.6895, 139.6917)   # Tokyo, Japon
]

# Afficher la liste des coordonnées
for coord in coordonnees:
    print(f"Latitude: {coord[0]}, Longitude: {coord[1]}")



Latitude: 48.8566, Longitude: 2.3522
Latitude: 40.7128, Longitude: -74.006
Latitude: 34.0522, Longitude: -118.2437
Latitude: 51.5074, Longitude: -0.1278
Latitude: 35.6895, Longitude: 139.6917


In [ ]:
# Utilisez NumPy pour calculer la distance entre deux points (latitude, longitude).